### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by surferjoeit** [gateship-one/odyssey#61]
Hello,
first of all many thanks for this nice app.
I want to submit a possible bug: on Android 5.0.2 the equalizer starts only from playback screen and not from settings, and most of all even if i modify equalizer settings this doesn't affect the sound.

**Comment by djselbeck** [comment]
Strange. It worked when I last tested it. But for my smartphone the equalizer seems to be completely broken. Not even google music works at the moment (Sony Xperia XZ Android 7) which means that I cannot test Odyssey at the moment. I'll try to get another device of me running.

**Comment by djselbeck** [comment]
It worked at first on my LineageOS runnin Bq M5 and now stopped working. I think it is related to another app on the device.

I'll try to figure out which one.

**Comment by surferjoeit** [comment]
Maybe stock player?

**Comment by djselbeck** [comment]
I don't know. On my Sony not even the sony app has a working equalizer at the moment. Something weird is going on here.

On my Bq it is not deterministic. sometimes it works sometimes not. I already tried deinstalling all the facebook applications and twitter. No luck on my sony so far. I'm a bit reluctant to wipe the device as i'm going on vacation in a few days :)

**Comment by djselbeck** [comment]
Probably is fixed with the last few commits : https://github.com/gateship-one/odyssey/commit/ec2247aaa463018f6f551844f4333d337f759f1e

**Comment by surferjoeit** [comment]
Thanks, i'll check it with next release.

**Comment by gnome17** [comment]
We released a new version which includes the fix for your issue. It is already available at Google Play and will be available on F-Droid in the next few days we think.

If your issue reoccurs please reopen the issue.

**Comment by surferjoeit** [comment]
Hello,
i finally managed to download it with F-Droid. It seems that nothing changed and the equalizer still doesn't work... I had not enough time to deeply test it but apparently the behavior is the same as previous release.
I also tried to uninstall it and re-install but with no luck.

Thanks
All the best
Francesco

**Comment by surferjoeit** [comment]
Hello again,
i tested it and confirm that on my device nothing changed. I still can't open equalizer from menu drawer.
I can open it from playback screen but it doesn't work. It seems i can just turn it on and off but audio output doesn't change.
Audio output is only modified by the equalizer when i open and use it from stock music player and the setting is then preserved when playing music with odyssey with no possibility to modify it.
Hope my description is clear enough....
Thanks
Francesco
